#! /bin/sh

if [ "$1" = "purge" ] ; then
    if [ -d /var/log/freedns-update/ ]; then
         rm -r /var/log/freedns-update/
    fi

    if [ -d /var/run/freedns-update/ ]; then
        rm -r /var/run/freedns-update/
    fi

    if [ -e /var/log/upstart/freedns-update.log ]; then
        rm -r /var/log/upstart/freedns-update.log
    fi
fi

#DEBHELPER#
exit 0;
