#! /bin/sh

isUpstart() {
    /sbin/init --version 2>/dev/null | grep -q 'upstart'
    #echo "result=$?"
    if [ "$?" = "0" ]; then
        return 0
    else 
        return 1
    fi
}

isSystemd() {
    /bin/systemctl 2>/dev/null | grep -q '\-\.mount'
    #echo "result=$?"
    if [ "$?" = "0" ]; then
        return 0
    else 
        return 1
    fi
}

if isUpstart; then
	PID=$(status "freedns-update" 2>/dev/null | awk '/[0-9]$/ { print $NF }')
	[ -z "$PID" ] || kill -HUP $PID
	start freedns-update
fi

if isSystemd; then
	systemctl enable freedns-update
	systemctl start freedns-update
fi

#DEBHELPER#
exit 0
