#! /bin/sh

isUpstart() {
    /sbin/init --version 2>/dev/null | grep -q 'upstart'
    #echo "result=$?"
    if [ "$?" = "0" ]; then
        return 0
    else 
        return 1
    fi
}

isSystemd() {
    /bin/systemctl 2>/dev/null | grep -q '\-\.mount'
    #echo "result=$?"
    if [ "$?" = "0" ]; then
        return 0
    else 
        return 1
    fi
}

if isUpstart; then
	stop freedns-update || echo "could not stop freedns-update"
fi

if isSystemd; then
	if systemctl is-active freedns-update; then
		systemctl stop freedns-update
	fi
	systemctl disable freedns-update
fi

#DEBHELPER#
exit 0
